name: tictactoe-server
data_dir: ""

logger:
  level: "INFO"
  stdout: true
  file: ""

console:
  port: 7351
  username: "admin"
  password: "password"
  signing_key: "defaultkey"
  token_expiry_sec: 86400

socket:
  server_key: "defaultkey"
  port: 7350
  max_message_size_bytes: 4096
  read_buffer_size_bytes: 4096
  write_buffer_size_bytes: 4096
  ping_period_ms: 15000
  pong_wait_ms: 25000
  write_wait_ms: 10000

database:
  address:
    - "postgres:localdb@postgres:5432/nakama"
  conn_max_lifetime_ms: 60000
  max_open_conns: 100
  max_idle_conns: 100

runtime:
  env:
    - "NODE_ENV=development"
  js_entrypoint: "/nakama/data/build/tictactoe.js"
